### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by atsunii** [atsunii/furima-32583#10]
自身のフリマアプリのURL
 https://furima-32583.herokuapp.com/

Basic認証のIDとパスワード
ID admin  パスワード 2222

出品者用のメールアドレスとパスワード 
メールアドレス b@b  パスワード aaa555

購入者用のメールアドレスとパスワード
メールアドレス c@c  パスワード aaa555

購入用カードの番号・期限・セキュリティコード 
カード番号　4242424242424242
期限　現在より未来の日付
セキュリティコード　123

**Comment by mutorisa** [comment]
@atsunii さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正が必要な箇所]**

- [ ] **①商品出品ページで適切では無い値が入力され「出品するボタン」が押されたら、（情報は保存されず）出品ページに戻りエラーメッセージが表示されるよう実装しましょう**
→現在は以下添付画像の通り、意図しないエラーが出てしまう状態です。
<img width="559" alt="スクリーンショット 2021-01-13 18 38 19" src="https://user-images.githubusercontent.com/65144927/104435047-48a07a80-55cf-11eb-8e9c-6ec7fc2068b0.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by atsunii** [comment]
訂正しました。

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/65144927/104531198-f869fc80-5650-11eb-8a7a-b933b36ea1c2.png)

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
